from django.urls import path,  include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('', views.base, name="base"),
    path('home.html', views.home, name="home"),
    path('news.html', views.news, name="news"),
    path('news_category.html', views.news_category, name='news_category'),
    path('add_stock.html', views.add_stock, name='add_stock'),
    path('delete/<stock_id>', views.delete, name="delete"),
    path('mydelete/<stock_id>', views.mydelete, name="mydelete"),
    path('portfolio.html', views.portfolio, name="portfolio"),
    path('setting.html', views.setting, name="setting"),
    path('account.html', views.account, name="account"),
    path('about.html', views.about, name="about"),
    path('login.html', views.login, name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('register.html', views.register, name='register'),
    # path('dashboard.html', views.dashboard, name='dashboard'),
    path('account_settings.html', views.account_setting, name='account_setting'),
    path('profile_settings.html', views.profile_setting, name='profile_setting'),
    path('change_pass/<id>', views.change_pass, name='change_pass'),
    path('charts.html', views.charts_display, name='charts_display'),
    path('charts_data/<symbol>', views.charts_data, name='charts_data'),
    path('mystock.html', views.mystock, name='mystock'),
    path('portfolio_data', views.portfolio_data, name='protfolio_data'),
    path('portfolio_chart.html', views.portfolio_chart, name='portfolio_chart'),
    path('aapl.html', views.aapl, name='aapl'),
    path('goog.html', views.goog, name='goog'),
    path('bac.html', views.bac, name='bac'),
    path('amzn.html', views.amzn, name='amzn'),
    path('mstf.html', views.mstf, name='mstf'),
    path('tif.html', views.tif, name='tif'),
    path('search/', views.search, name="search"),
    path('search_news/', views.search_news, name="search_news"),
]
